from __future__ import annotations

import json
import logging
import os
from typing import Any, Dict, List, Optional

from google import genai
from google.genai import types
from google.genai.errors import ServerError
from tenacity import (
    retry,
    retry_if_exception_type,
    stop_after_attempt,
    wait_exponential,
)

logger = logging.getLogger(__name__)


_MODEL = "gemini-2.5-flash"
_TEMPERATURE = 0.4


SYSTEM_PROMPT = """
You are an elite Patent Attorney specializing in drafting provisional patent applications for deep tech, AI, and software. Your task is to take extracted technical features and draft formal provisional patent claims.

RULES FOR DRAFTING:
1. Use standard formal patent legalese (e.g., "1. A system comprising...", "2. The system of claim 1, further comprising...").
2. Draft one primary "independent claim" covering the core architecture/methodology.
3. Draft 2-3 "dependent claims" that expand on specific technical nuances, algorithms, or hardware configurations provided in the extracted data.
4. Output your response strictly as a cleanly formatted Markdown string, using bolding for key terms.
5. Do not include any conversational filler, introductory remarks, or markdown code blocks (like ```markdown). Just the draft.
""".strip()


USER_PROMPT_TEMPLATE = """
Draft formal provisional patent claims based on the following extracted technical features:

EXTRACTED CLAIMS:
{claims_json}
""".strip()


_CRITICAL_FALLBACK_DRAFT: str = """\
**Independent Claim**

1. A **verifiable execution system** comprising:
   - a **processor architecture** providing a plurality of isolated execution domains;
   - a **specialized intermediate runtime environment** instantiated between said execution domains, the intermediate runtime configured to mediate inter-domain transitions and validate execution pathways prior to instruction issuance;
   - one or more memory units storing instructions that, when executed, cause the system to perform the methods of the claims herein,
   wherein said system establishes provable execution integrity guarantees across the plurality of execution domains without requiring trust-boundary crossings during normal operation.

**Dependent Claims**

2. The system of claim 1, further comprising an **application-agnostic verification engine** configured to validate execution traces and parameters of arbitrary user computations within an untrusted execution domain without exposing underlying confidential parameters to a verifying party.

3. The system of claim 1, wherein the specialized intermediate runtime environment provides **cryptographic attestation** binding verified execution traces to a hardware root of trust, enabling third-party verification of the integrity of the executed computation.

4. The system of claim 2, wherein said verification engine is configured to validate inference parameters and execution pathways of a **deep neural network** without disclosing model weights, gradient information, or intermediate activations to the verifying party.

5. The system of claim 1, wherein the specialized intermediate runtime environment operates with bounded computational overhead suitable for **real-time operational deployment** on resource-constrained hardware.

---

*This provisional draft is generated by the GapSight pipeline for technical review only. Any formal patent filing must be reviewed and signed off by a licensed Intellectual Property attorney.*
"""


def _resolved_api_key() -> Optional[str]:
    api_key = os.getenv("GOOGLE_API_KEY")
    if not api_key or api_key.strip().lower() in {"", "replace-me", "your-key-here"}:
        return None
    return api_key.strip()


@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=2, max=6),
    retry=retry_if_exception_type(ServerError),
    reraise=True,
)
async def _call_gemini_for_draft(
    client: "genai.Client",
    user_prompt: str,
) -> str:
    response = await client.aio.models.generate_content(
        model=_MODEL,
        contents=user_prompt,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_PROMPT,
            temperature=_TEMPERATURE,
        ),
    )
    return (response.text or "").strip()


async def draft_claims(extracted_claims: List[Dict[str, Any]]) -> str:
    try:
        if not extracted_claims:
            return _CRITICAL_FALLBACK_DRAFT

        api_key = _resolved_api_key()
        if api_key is None:
            logger.warning("GOOGLE_API_KEY not configured; returning fallback draft.")
            return _CRITICAL_FALLBACK_DRAFT

        claims_json = json.dumps(extracted_claims, indent=2, ensure_ascii=False)
        user_prompt = USER_PROMPT_TEMPLATE.format(claims_json=claims_json)

        client = genai.Client(api_key=api_key)
        content = await _call_gemini_for_draft(client, user_prompt)

        if not content:
            logger.warning("Agent 4 returned empty content; using critical fallback.")
            return _CRITICAL_FALLBACK_DRAFT

        return content

    except Exception as e:
        print(f"Agent 4 Critical Fallback triggered due to error: {e}")
        logger.exception("Agent 4 critical fallback triggered: %s", e)
        return _CRITICAL_FALLBACK_DRAFT
